import type { Metadata } from "next";
import "./globals.css";
import { OrbitronFont, RubikMonoOneFont } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OrbitronFont.variable} ${RubikMonoOneFont.variable} w-screen h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
